Repository DeveloperAcademy-POSTECH/MC3-Team17-Shaka, pull requests merged in 2022-07, with the labels that each got.

#2 🔥 : gitignore SwiftPackageManager 삭제
  shaka/.gitignore
  shaka/shaka.xcodeproj/project.pbxproj
Labels: Status: 머지 요청

#8 애플 로그인 및 토큰 관리
  shaka/.gitignore
  shaka/shaka.xcodeproj/project.pbxproj
  shaka/shaka/AppDelegate.swift
  shaka/shaka/Base.lproj/Main.storyboard
  shaka/shaka/Info.plist
  shaka/shaka/KeyChain.swift
  shaka/shaka/Login.storyboard
  shaka/shaka/LoginViewController.swift
  shaka/shaka/shaka.entitlements
Labels: Status: 리뷰 요청, Status: 머지 요청

#9 🚚 : 폴더구조 변경
  shaka/shaka.xcodeproj/project.pbxproj
  shaka/shaka/Controller/LoginViewController.swift
  shaka/shaka/Controller/ViewController.swift
  shaka/shaka/View/Base.lproj/LaunchScreen.storyboard
  shaka/shaka/View/Base.lproj/Main.storyboard
  shaka/shaka/View/Login.storyboard
Labels: Status: 머지 요청

#12 Timer View UI 및 기능 구현
  shaka/shaka.xcodeproj/project.pbxproj
  shaka/shaka/Assets.xcassets/StartButtonColor.colorset/Contents.json
  shaka/shaka/Assets.xcassets/StopButtonColor.colorset/Contents.json
  shaka/shaka/Controller/TimerViewController.swift
  shaka/shaka/View/Base.lproj/Main.storyboard
  shaka/shaka/View/Timer.storyboard
  shaka/shaka/View/TimerButton.swift
Labels: Status: 리뷰 요청

#15 메인페이지 UI 변경 및 Push 알림을 위한 세팅
  shaka/shaka.xcodeproj/project.pbxproj
  shaka/shaka/Assets.xcassets/ThunderIcon.imageset/Asset 3@2x.png
  shaka/shaka/Assets.xcassets/ThunderIcon.imageset/Contents.json
  shaka/shaka/Assets.xcassets/WaveIcon.imageset/Asset 2@2x.png
  shaka/shaka/Assets.xcassets/WaveIcon.imageset/Contents.json
  shaka/shaka/Assets.xcassets/WindIcon.imageset/Asset 1@2x.png
  shaka/shaka/Assets.xcassets/WindIcon.imageset/Contents.json
  shaka/shaka/Controller/PushViewController.swift
  shaka/shaka/Controller/ViewController.swift
  shaka/shaka/Controller/WeatherTVC.swift
  shaka/shaka/View/Base.lproj/Main.storyboard
  shaka/shaka/View/Timer.storyboard
  shaka/shaka/View/WeatherNotification.storyboard
Labels: Status: 리뷰 요청, Status: 머지 요청

#19 ✨ : ContainerView 하나 삭제하고 부모뷰로 이동 및 데이터 연결 작업 진행
  shaka/shaka.xcodeproj/project.pbxproj
  shaka/shaka/Controller/SurfDateCollectionViewCell.swift
  shaka/shaka/Controller/SurfRecordGraphViewController.swift
  shaka/shaka/Controller/SurfRecordShowViewController.swift
  shaka/shaka/Controller/SurfRecordViewController.swift
  shaka/shaka/DataModel/MockData.swift
  shaka/shaka/DataModel/SurfRecordData.swift
  shaka/shaka/Info.plist
  shaka/shaka/View/SurfRecord.storyboard
Labels: Status: 머지 요청

#22 ✨ : 웨더뷰 및 네비게이션 컨트롤러 추가
  shaka/shaka/View/Base.lproj/Main.storyboard
  shaka/shaka/View/WeatherNotification.storyboard
Labels: Status: 리뷰 요청, Status: 머지 요청

#23 :sparkles: Watch Interface added
  shaka/shakaWatch WatchKit Extension/Assets.xcassets/Complication.complicationset/Circular.imageset/Contents.json
  shaka/shakaWatch WatchKit Extension/Assets.xcassets/Complication.complicationset/Contents.json
  shaka/shakaWatch WatchKit Extension/Assets.xcassets/Complication.complicationset/Extra Large.imageset/Contents.json
  shaka/shakaWatch WatchKit Extension/Assets.xcassets/Complication.complicationset/Graphic Bezel.imageset/Contents.json
  shaka/shakaWatch WatchKit Extension/Assets.xcassets/Complication.complicationset/Graphic Circular.imageset/Contents.json
  shaka/shakaWatch WatchKit Extension/Assets.xcassets/Complication.complicationset/Graphic Corner.imageset/Contents.json
  shaka/shakaWatch WatchKit Extension/Assets.xcassets/Complication.complicationset/Graphic Extra Large.imageset/Contents.json
  shaka/shakaWatch WatchKit Extension/Assets.xcassets/Complication.complicationset/Graphic Large Rectangular.imageset/Contents.json
  shaka/shakaWatch WatchKit Extension/Assets.xcassets/Complication.complicationset/Modular.imageset/Contents.json
  shaka/shakaWatch WatchKit Extension/Assets.xcassets/Complication.complicationset/Utilitarian.imageset/Contents.json
  shaka/shakaWatch WatchKit Extension/Assets.xcassets/Contents.json
  shaka/shakaWatch WatchKit Extension/ComplicationController.swift
  shaka/shakaWatch WatchKit Extension/ExtensionDelegate.swift
  shaka/shakaWatch WatchKit Extension/Info.plist
  shaka/shakaWatch WatchKit Extension/InterfaceController.swift
  shaka/shakaWatch/Assets.xcassets/AccentColor.colorset/Contents.json
  shaka/shakaWatch/Assets.xcassets/AppIcon.appiconset/Contents.json
  shaka/shakaWatch/Assets.xcassets/Contents.json
  shaka/shakaWatch/Base.lproj/Interface.storyboard
Labels: Status: 머지 요청

#24 🍱 : 앱 아이콘 추가
  shaka/shaka/Assets.xcassets/AppIcon.appiconset/100.png
  shaka/shaka/Assets.xcassets/AppIcon.appiconset/1024.png
  shaka/shaka/Assets.xcassets/AppIcon.appiconset/114.png
  shaka/shaka/Assets.xcassets/AppIcon.appiconset/120.png
  shaka/shaka/Assets.xcassets/AppIcon.appiconset/144.png
  shaka/shaka/Assets.xcassets/AppIcon.appiconset/152.png
  shaka/shaka/Assets.xcassets/AppIcon.appiconset/167.png
  shaka/shaka/Assets.xcassets/AppIcon.appiconset/172.png
  shaka/shaka/Assets.xcassets/AppIcon.appiconset/180.png
  shaka/shaka/Assets.xcassets/AppIcon.appiconset/196.png
  shaka/shaka/Assets.xcassets/AppIcon.appiconset/20.png
  shaka/shaka/Assets.xcassets/AppIcon.appiconset/216.png
  shaka/shaka/Assets.xcassets/AppIcon.appiconset/29.png
  shaka/shaka/Assets.xcassets/AppIcon.appiconset/40.png
  shaka/shaka/Assets.xcassets/AppIcon.appiconset/48.png
  shaka/shaka/Assets.xcassets/AppIcon.appiconset/50.png
  shaka/shaka/Assets.xcassets/AppIcon.appiconset/55.png
  shaka/shaka/Assets.xcassets/AppIcon.appiconset/57.png
  shaka/shaka/Assets.xcassets/AppIcon.appiconset/58.png
  shaka/shaka/Assets.xcassets/AppIcon.appiconset/60.png
  shaka/shaka/Assets.xcassets/AppIcon.appiconset/72.png
  shaka/shaka/Assets.xcassets/AppIcon.appiconset/76.png
  shaka/shaka/Assets.xcassets/AppIcon.appiconset/80.png
  shaka/shaka/Assets.xcassets/AppIcon.appiconset/87.png
  shaka/shaka/Assets.xcassets/AppIcon.appiconset/88.png
  shaka/shaka/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: Status: 머지 요청

#25 :sparkles: Main과 SurfRecord 스토리보드 연결
  .DS_Store
  shaka/shaka.xcodeproj/project.pbxproj
  shaka/shaka/View/Base.lproj/Main.storyboard
  shaka/shaka/View/SurfRecord.storyboard
  shaka/shakaWatch WatchKit Extension/ExtensionDelegate.swift
Labels: Status: 머지 요청
