Repository DeveloperAcademy-POSTECH/MC3-Team17-Shaka, pull requests merged in 2022-08, with the labels that each got.

#28 💄 : 메인페이지 디테일링 수정
  shaka/shaka/View/Base.lproj/Main.storyboard
Labels: Status: 머지 요청

#29 📝 리드미 파일 추가
  README.md
Labels: Status: 머지 요청

#31 :art: Add watch timer under deactive mode
  shaka/shakaWatch WatchKit Extension/ExtensionDelegate.swift
  shaka/shakaWatch WatchKit Extension/InterfaceController.swift
  shaka/shakaWatch WatchKit Extension/ShakaApp.mobileprovision
  shaka/shakaWatch WatchKit Extension/shaka.entitlements
  shaka/shakaWatch WatchKit Extension/shakaIdentifier.p12
Labels: Status: 리뷰 요청, Status: 머지 요청

#32 ✨ 워치, 앱 연동 WIP
  .DS_Store
  .gitignore
  README.md
  shaka/shaka/Controller/TimerViewController.swift
  shaka/shaka/Controller/ViewController.swift
  shaka/shakaWatch WatchKit Extension/InterfaceController.swift
Labels: Status: 리뷰 요청, Status: 머지 요청, Status: WIP
